version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - 5173:5173
    command: npm start
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - NODE_ENV=test
    command: npm test