name: Continous Integration and Delivery

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
