name: Continous Integration and Delivery

on:
  push:
    branches: [master]

jobs:
  test:
    name: Install dependencies and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
  docker:
    name: Create docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t rishabh/docker-frontend .
